# Generated by Django 5.0.1 on 2024-02-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_item_remove_employee_name_employee_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transactiondate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
