# Generated by Django 5.0.2 on 2024-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='incart',
            field=models.BooleanField(default=False),
        ),
    ]
