# Generated by Django 5.0.2 on 2024-02-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_orders_incart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(choices=[('initiated', 'initiated'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='initiated', max_length=20),
        ),
    ]
