# Generated by Django 5.0.2 on 2024-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_orders_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='itemqunatity',
            field=models.IntegerField(default=0),
        ),
    ]
