# Generated by Django 5.0.2 on 2024-02-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_orders_itemqunatity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='receipeid',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.item'),
        ),
    ]
