# Generated by Django 5.0.2 on 2024-02-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_orders_receipeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='itemqunatity',
            new_name='itemquantity',
        ),
    ]
