# Generated by Django 5.0.1 on 2024-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_itemqunatity_orders_itemquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeorderhistory',
            name='transactiondate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
