# Generated by Django 5.0.1 on 2024-02-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_employeeorderhistory_transactiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='totalquantities',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
