# Generated by Django 5.0.1 on 2024-02-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_item_totalquantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='isplacedbyadmin',
            field=models.BooleanField(default=False),
        ),
    ]
