# Generated by Django 5.0.1 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_orders_isplacedbyadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isguestlogin',
            field=models.BooleanField(default=False),
        ),
    ]
