# Generated by Django 5.0.1 on 2024-03-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employee_isguestlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('receipe', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='Images')),
                ('totalquantities', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
